# Generated by Django 5.0.3 on 2024-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0005_delete_person_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=2, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
