# Generated by Django 5.0.3 on 2024-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0007_alter_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
